name: Build (release)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check & Clippy
      run: cargo check --verbose && cargo clippy --verbose -- -D warnings
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose --release